"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { motion } from "framer-motion"
import { ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"

interface BodyPartExercises {
  legs: string
  back: string
  chest: string
  arms: string
  core: string
  fullText: string
}

export default function AllBodyPartsPage() {
  const [exercises, setExercises] = useState<BodyPartExercises | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [expandedSection, setExpandedSection] = useState<string>("legs")

  useEffect(() => {
    const fetchExercises = async () => {
      try {
        setLoading(true)
        const response = await fetch("/api/body-parts-exercises")
        if (!response.ok) throw new Error("Failed to fetch exercises")
        const data = await response.json()
        setExercises(data)
        setError(null)
      } catch (err) {
        console.error("Error fetching exercises:", err)
        setError("Failed to load exercises. Please try again.")
      } finally {
        setLoading(false)
      }
    }

    fetchExercises()
  }, [])

  const bodyParts = [
    { key: "legs", label: "Legs", color: "from-blue-500 to-blue-600" },
    { key: "back", label: "Back", color: "from-purple-500 to-purple-600" },
    { key: "chest", label: "Chest", color: "from-red-500 to-red-600" },
    { key: "arms", label: "Arms", color: "from-yellow-500 to-yellow-600" },
    { key: "core", label: "Core", color: "from-green-500 to-green-600" },
  ]

  const handleRefresh = () => {
    window.location.reload()
  }

  return (
    <main className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8">
        <Link href="/home" className="inline-flex items-center gap-2 text-primary hover:underline mb-8">
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
          <h1 className="text-4xl font-bold mb-2">All Body Parts Workouts</h1>
          <p className="text-muted-foreground">Comprehensive exercises for every major muscle group generated by AI</p>
        </motion.div>

        {loading && (
          <div className="flex items-center justify-center py-12">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
          </div>
        )}

        {error && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="bg-red-50 border border-red-200 rounded-lg p-4 text-red-700 flex items-center justify-between"
          >
            <span>{error}</span>
            <Button onClick={handleRefresh} className="ml-4">
              Retry
            </Button>
          </motion.div>
        )}

        {exercises && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ staggerChildren: 0.1 }}>
            {/* Body Part Buttons */}
            <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-8">
              {bodyParts.map((part) => (
                <motion.button
                  key={part.key}
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={() => setExpandedSection(part.key)}
                  className={`${
                    expandedSection === part.key
                      ? `bg-gradient-to-br ${part.color} text-white`
                      : "bg-gray-200 text-gray-800 hover:bg-gray-300"
                  } font-bold py-3 px-4 rounded-lg transition-all`}
                >
                  {part.label}
                </motion.button>
              ))}
            </div>

            {/* Exercise Display */}
            <motion.div
              key={expandedSection}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="bg-white rounded-2xl p-8 shadow-lg border border-gray-200"
            >
              <h2 className="text-3xl font-bold mb-6 capitalize">
                {bodyParts.find((p) => p.key === expandedSection)?.label} Exercises
              </h2>
              <div className="prose prose-sm max-w-none text-gray-700">
                {exercises[expandedSection as keyof BodyPartExercises] ? (
                  <pre className="bg-gray-50 p-4 rounded-lg whitespace-pre-wrap text-sm leading-relaxed overflow-x-auto">
                    {exercises[expandedSection as keyof BodyPartExercises]}
                  </pre>
                ) : (
                  <p className="text-muted-foreground">Loading exercises...</p>
                )}
              </div>
            </motion.div>

            {/* Full Routine */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className="mt-8 bg-blue-50 rounded-2xl p-8 border border-blue-200"
            >
              <h2 className="text-2xl font-bold mb-4 text-blue-900">Complete Routine Overview</h2>
              <details className="text-blue-900">
                <summary className="cursor-pointer font-bold hover:text-blue-700 mb-3">
                  Click to view full routine
                </summary>
                <pre className="bg-white p-4 rounded-lg whitespace-pre-wrap text-sm border border-blue-200 mt-3 overflow-x-auto">
                  {exercises.fullText}
                </pre>
              </details>
            </motion.div>
          </motion.div>
        )}
      </div>
    </main>
  )
}
